.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.TH "aspsms-t.notify" "1" "1.3.0"
.SH NAME
aspsms-t.notify \- Delivery notification script for aspsms-t
.SH SYNOPSIS
aspsms-t.notify?xml=notify,,,004179xyzx,,,$USERKEY,,,<Originator>,,,<MessageData>
.SH DESCRIPTION
Script is a xml stream...
.SH SEE ALSO
\fBaspsms-t\fR(1)
.PP
.SH FILES
.PD 0
.TP 
.FN aspsms-t.notify.xml
The aspsms-t.notify configuration file
.SH RESOURCES
.TP
aspsms-t git website 
http://github.com/micressor/aspsms-t
