aspsms-t.pl usr/bin
aspsmstlog.pm usr/share
CheckNotification.pm usr/share
ConnectionASPSMS.pm usr/share
Connection.pm usr/share
ContactCredits.pm usr/share
DiscoNetworks.pm usr/share
GetNetworksFees.pm usr/share
Jid.pm usr/share
Message.pm usr/share
Regex.pm usr/share
Sendaspsms.pm usr/share
ShowBalance.pm usr/share
Storage.pm usr/share
UCS2.pm usr/share
userhandler.pm usr/share
xmlmodel.pm usr/share

