#!/bin/sh

set -e

# Install application user, if it does not exist.
id aspsms 2>&1 >/dev/null
[ "$?" -ne "0" ] && useradd -m -d /var/cache/aspsms aspsms

# Copy example config file to /etc/aspsms 
if [ ! -r /etc/aspsms/aspsms-t.xml.dist ] && [ ! -r /etc/aspsms/aspsms-t.xml ];
then
  cp /usr/share/doc/aspsms-t/examples/aspsms-t.xml.dist /etc/aspsms
fi

# Create spooldir if it does not exist.
if [ ! -d /var/cache/aspsms/spool ];
then
  mkdir -p /var/cache/aspsms/spool
fi

##DEBHELPER##
