#!/bin/sh

set -e

# Install application user, if it does not exist.
if ! id aspsms 2>&1 >/dev/null;
then
  useradd -d /var/cache/aspsms aspsms
  # Fix permissions for application
  chown aspsms: /var/cache/aspsms /etc/aspsms /var/lib/aspsms
fi

if [ ! -r /etc/aspsms/aspsms-t.xml.dist ] && [ ! -r /etc/aspsms/aspsms-t.xml ];
then
  install -g aspsms -o aspsms -m 640  \
	/usr/share/doc/aspsms-t/examples/aspsms-t.xml.dist /etc/aspsms
fi

##DEBHELPER##
